name: Scheduled Task

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run command
        run: echo "Hello World"
